// harness-installers/shared/build-helpers/manifest-parity.js —
// Build-time parity check between a plugin's built _install-source/ payload and
// its committed manifest catalog.
//
// Unlike the standard installer's manifests (generated by emit-manifest.js, with
// a sha256 per file — so a rebuild + `git diff` gate detects drift), the plugin
// manifests are HAND-AUTHORED path catalogs ({ sourcePath, destinationPath,
// ownership }, no sha). The build only COPIES them verbatim into output/, so a
// git-diff gate can never notice when the installable payload and the catalog
// drift apart. This helper closes that gap by comparing the two in both
// directions:
//   missing — manifest sourcePath entries with no corresponding file in the
//             built output (install would fail with ENOENT).
//   orphans — files staged under output/_install-source/ that no manifest entry
//             claims (they would silently never install).
//
// The UI bundle (_install-source/ui.tgz) is intentionally excluded: it is a
// hydration tarball extracted wholesale into ~/.radorc/ui/ by the installer's
// UI-hydration step, never a manifest-copied file. (This mirrors the standard
// installer's HYDRATION_EXCLUDED_PREFIXES treatment of `ui/` in emit-manifest.js.)

import fs from 'node:fs';
import path from 'node:path';

const INSTALL_SOURCE_DIR = '_install-source';

// Paths under _install-source/ that are NOT governed by the manifest catalog
// (hydration assets extracted separately by the installer). POSIX, relative to
// outputDir.
const HYDRATION_EXCLUDED = new Set([`${INSTALL_SOURCE_DIR}/ui.tgz`]);

// VCS placeholders that keep otherwise-empty runtime-config/ directories in git
// (e.g. templates/.gitkeep, action-events/.gitkeep). The build copies them into
// _install-source/ along with everything else, but they are not installable
// payload and the hand-authored manifests correctly omit them, so the parity
// check must ignore them too. Matched by basename, anywhere in the tree.
const VCS_PLACEHOLDERS = new Set(['.gitkeep', '.gitignore']);

/**
 * Recursively collect file paths (not directories) under `dir`, as absolute
 * paths. Empty directories (e.g. the action-events `custom/` slot) contribute
 * nothing, which is correct: the manifest lists files, not directories.
 *
 * @param {string} dir
 * @param {string[]} [acc]
 * @returns {string[]}
 */
function walkFiles(dir, acc = []) {
  if (!fs.existsSync(dir)) return acc;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walkFiles(full, acc);
    else acc.push(full);
  }
  return acc;
}

/**
 * Compares a plugin's built _install-source/ tree against its manifest catalog.
 *
 * @param {{ outputDir: string, manifest: { files?: Array<{ sourcePath: string }> } }} opts
 *   outputDir — the plugin's build `output/` directory. Manifest sourcePaths
 *               (e.g. `_install-source/orchestration.yml`) are resolved relative
 *               to it.
 *   manifest  — the parsed committed manifest (v<version>.json).
 * @returns {{ missing: string[], orphans: string[] }} POSIX-normalised,
 *   sorted relative paths.
 */
export function checkInstallSourceParity({ outputDir, manifest }) {
  const manifestSources = new Set((manifest.files ?? []).map((f) => f.sourcePath));

  // missing — every manifest sourcePath must exist on disk in the built output.
  const missing = [];
  for (const sourcePath of manifestSources) {
    if (!fs.existsSync(path.join(outputDir, sourcePath))) missing.push(sourcePath);
  }

  // orphans — every file under output/_install-source/ must be claimed by the
  // manifest (excluding hydration assets such as ui.tgz).
  const orphans = [];
  for (const abs of walkFiles(path.join(outputDir, INSTALL_SOURCE_DIR))) {
    const rel = path.relative(outputDir, abs).split(path.sep).join('/');
    if (HYDRATION_EXCLUDED.has(rel)) continue;
    if (VCS_PLACEHOLDERS.has(path.basename(rel))) continue;
    if (!manifestSources.has(rel)) orphans.push(rel);
  }

  missing.sort();
  orphans.sort();
  return { missing, orphans };
}
